defaults:
  - model: txt2img
  - computer: 1-gpu
  - data: laion6_cc12m
  - logger: wandb
  - _self_

load_weight_from_checkpoint: ???

trainer:
  _target_: lightning.pytorch.Trainer
  max_steps: 300000
  deterministic: True
  devices: ${computer.devices}
  accelerator: ${computer.accelerator}
  strategy: ${computer.strategy}
  log_every_n_steps: 1
  num_nodes: ${computer.num_nodes}
  precision: ${computer.precision}
  gradient_clip_val: 1.0
  
checkpoints:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${checkpoint_dir}/${experiment_name}
  save_last: True
  save_on_train_epoch_end: True
  save_top_k: -1
  enable_version_counter: False
  every_n_train_steps: 10000
  auto_insert_metric_name: False

progress_bar:
  _target_: lightning.pytorch.callbacks.TQDMProgressBar
  refresh_rate: ${computer.progress_bar_refresh_rate}

seed: 3407
data_dir: ${root_dir}/datasets
root_dir:  ${hydra:runtime.cwd}
checkpoint_dir: ${root_dir}/checkpoints
experiment_name_suffix: base
experiment_name: ${data.name}_${model.name}_${experiment_name_suffix}
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/${experiment_name}
  job:
    chdir: true