_target_: model.network.imagediffusion.TextConditionalDiHpp
n_timesteps: 250
text_tokens_dim: ${data.text_tokens_dim}
input_dim: 4
dim: 384
im_size: ${data.size}
kernel_size: 2
n_layers: 12
order: 2
order_expand: 2
ffw_expand: 3
dropout: 0.0
n_registers: 16